Sct 107 change tier plan
metlapp/webapp pull request #11
Opened 2021-02-23 17:48 UTC by JaycobDuffel

2021-02-23 21:43 UTC, katiemcgoff commented on package.json
> +    "dotenv": "^6.2.0"
Did this end up being used? 

I love the idea of a .env file instead of environment.js if we can make that work. But I'm not seeing it in the checked-in code.

2021-02-23 21:48 UTC, katiemcgoff commented on src/app/Components/Stripe/StripeModal.js
> +const stripeTestPromise = loadStripe('pk_test_SOwjvkbv16CkAfalfAqQDowQ009LxwrwD5');
Can we replace this with a single variable using a loadStripe() parameter from the environment.js file? So that we do not have to remember to change this before deploying to production (I definitely won't remember to change this 😛 )

2021-02-23 22:03 UTC, katiemcgoff commented on src/app/config/config.js
> +};
Let's pull values from environment.js rather than hardcode them. That way there is only one place in the whole codebase that needs to be changed when the app is built for local dev, staging, and prod.

2021-02-23 22:04 UTC, katiemcgoff commented on src/app/config/config.js
> +};
Also, feel free to fix the name typo of the environment.js file (enviroment -> environment).

2021-02-23 22:06 UTC, katiemcgoff requested changes
Some changes noted in-line. Additionally:

Between Pricing and UpgradePricing, we need to componentize the content. So if it's just the buttons and `user` functionality that are different, I'd say make props on the Pricing component to control the parts of the page you need to control. Or use the Pricing component in the UpgradePricing component with small tweaks to Pricing component. Either way, no duplicated content.

2021-02-23 22:10 UTC, katiemcgoff commented on src/app/Components/Stripe/StripeModal.js
> +const stripeTestPromise = loadStripe('pk_test_SOwjvkbv16CkAfalfAqQDowQ009LxwrwD5');
Shoot, I just realized these are the real promises, aren't they? Ie: that production promise shouldn't be out in the public world of github? 😄 

If that's the case, let's remove them asap and I'll see if they can be regenerated in Stripe.

2021-02-23 22:12 UTC, katiemcgoff commented on src/app/Components/Stripe/StripeModal.js
> +const stripeTestPromise = loadStripe('pk_test_SOwjvkbv16CkAfalfAqQDowQ009LxwrwD5');
Nevermind, I just read the docs. We're good.

2021-02-26 18:52 UTC, DawsonDease approved these changes

2021-02-26 19:22 UTC, katiemcgoff approved these changes

2021-02-26 19:24 UTC, merged