Sct 106 create contact page
metlapp/webapp pull request #3
Opened 2021-02-08 18:07 UTC by DawsonDease

2021-02-08 19:45 UTC, JaycobDuffel approved these changes

2021-02-08 22:56 UTC, katiemcgoff commented on src/app/Contact.js
> +            <Header title="Contact/Suppport" subTitle="We’d love to hear from you! Get in touch at info@metlapp.com and we’ll respond within 48 hours." />
Let's make the header "Contact & Support".

Instead of puting the content in the header subtitle, let's put it in a white-background section of the page. You may need to adjust the header spacing to make this look right.

2021-02-08 22:57 UTC, katiemcgoff requested changes
Style changes.

Also I see you've added "contact" to the header, that's good. It also needs to be added to the minimal header used for the Terms and Privacy pages.

2021-02-09 22:09 UTC, katiemcgoff requested changes
Looks great! One final change - Support is mis-spelled (three p's) in the page header but beyond that, good to go.

2021-02-09 22:17 UTC, katiemcgoff approved these changes

2021-02-09 23:32 UTC, merged