Sct 122 log in with slack
metlapp/webapp pull request #6
Opened 2021-02-09 23:38 UTC by DawsonDease

2021-02-10 16:40 UTC, JaycobDuffel requested changes

2021-02-10 16:40 UTC, JaycobDuffel commented on src/app/ReportsPage.js
> +const BillingPage = () =>{
Should this be ReportsPage and not BillingPage?

2021-02-10 17:03 UTC, DawsonDease commented on src/app/ReportsPage.js
> +const BillingPage = () =>{
yes! nice catch

2021-02-11 03:57 UTC, katiemcgoff commented
Looks good, but question about functionality - should we have the "from" querystring parameter in any link, such as from the main header?

2021-02-11 18:39 UTC, katiemcgoff approved these changes

2021-02-11 19:16 UTC, merged