SCT 101 Redirect upon oauth success
metlapp/webapp pull request #8
Opened 2021-02-18 19:48 UTC by DawsonDease

2021-02-18 21:54 UTC, katiemcgoff requested changes

2021-02-18 21:54 UTC, katiemcgoff commented on src/app/AppRoutes.js
> +          <Route path="/upgrading" component={ Upgrading} />
The URL of this page should be /upgrade, not /upgrading.

2021-02-19 00:21 UTC, katiemcgoff commented on src/app/AppRoutes.js
> +import upgrading from './UpgradePage';
This import is unused.

2021-02-19 00:21 UTC, katiemcgoff requested changes
one final change (unused import) then all good.

2021-02-19 02:58 UTC, katiemcgoff approved these changes

2021-02-19 17:05 UTC, JaycobDuffel approved these changes

2021-02-19 17:22 UTC, merged